name: flat-dir-campaign
date: 23 septembre 2020

setup:
  os: Linux CentOS 7 (x86_64)
  cpu: Intel XEON X5550
  ram: 32GB
  timeout: 1200
  memout: 16384

source:
  path: example/flat-dir/input/data2/
  format: flat-dir
data:
  file-name-meta:
    regex: ProblemFile-(.*)_(bs[012]{1})_(.*)
    experiment_ware: 2
    input_group: 1
  raw-data:
    - log-data: cpu_time
      regex: <global.*cpu="(\d+\.\d+)"
    - log-data: mem
      regex: <global.*mem="(\d+M\d+)"
    - log-data: result
      pattern: Stop="{word}"
